CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS states (
  id SERIAL PRIMARY KEY,
  census_code VARCHAR(20) UNIQUE,
  name VARCHAR(120) NOT NULL UNIQUE,
  slug VARCHAR(140) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS districts (
  id SERIAL PRIMARY KEY,
  state_id INTEGER NOT NULL REFERENCES states(id) ON DELETE CASCADE,
  census_code VARCHAR(20),
  name VARCHAR(140) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (state_id, slug)
);

CREATE TABLE IF NOT EXISTS subdistricts (
  id SERIAL PRIMARY KEY,
  district_id INTEGER NOT NULL REFERENCES districts(id) ON DELETE CASCADE,
  census_code VARCHAR(20),
  name VARCHAR(140) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (district_id, slug)
);

CREATE TABLE IF NOT EXISTS villages (
  id BIGSERIAL PRIMARY KEY,
  subdistrict_id INTEGER NOT NULL REFERENCES subdistricts(id) ON DELETE CASCADE,
  census_code VARCHAR(30),
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(220) NOT NULL,
  population INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (subdistrict_id, slug)
);

CREATE TABLE IF NOT EXISTS api_clients (

  id SERIAL PRIMARY KEY,

  name VARCHAR(160) NOT NULL,

  email VARCHAR(180) NOT NULL UNIQUE,

  api_key VARCHAR(80) NOT NULL UNIQUE,

  api_secret VARCHAR(64) NOT NULL,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  last_used_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

CREATE TABLE IF NOT EXISTS api_logs (
  id BIGSERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES api_clients(id) ON DELETE SET NULL,
  method VARCHAR(10) NOT NULL,
  path VARCHAR(300) NOT NULL,
  status_code INTEGER NOT NULL,
  response_time_ms INTEGER NOT NULL,
  ip_address VARCHAR(80),
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
